### PR TITLE
Phomemo M220 compatibility

### PR DESCRIPTION
**Pull request by bleriotx**
Code changes required to get Cups printer filter to work with M220 printer.
- Removed unneeded printer init codes.
- Modified the rendering code to send the print job in one sequence.

### CODE REVIEW

**Comment by vivier** [comment]
Please remove the code that is unused rather than to comment it out.
Don't add "2023-07-12 bleriotx - Fix for Phomemo M220 printer." in your comment the timestamp and the author are already given by the git log (with "git blame"), and you can put "Fix for Phomemo M220 printer" as the commit message header.
Merge both commits in one.
Did you test that this change doesn't break others printers support?

**Comment by bleriotx** [comment]
Sorry - I am new to all this and do not know the tools or the rules. This is why I was reluctant to get involved.
I have tested this on an M220, but do not own an M02 or M110 so cannot determine if it breaks them.

Probably better if somebody else reviews my findings in Issue #8 and determines if my changes are worthy.

**Comment by daig0rian** [comment]
OK! I will review and test it on M110 !

**Comment by daig0rian** [comment]
I have tested this pull request code and confirmed that it works on the M110 fine.
  PXL_20230713_130203656
PXL_20230713_131153051
 It is expected to work on M120 as well.

 The main point of this pull request is to make the bitstream output by the CUPS driver closer to that of the official Windows driver released by Phomemo. This will solve issue #13  and also make this CUPS driver more compatible with the other Mxxx series.

**Comment by daig0rian** [comment]
By the way, the M110 and M220 can output images with more than 255 lines in a single BLOCK MARKER (i.e. GS v 0 command) without any problem. As far as I can tell, the M110 can output a 2398 line (=30cm) image in one BLOCK MARKER, and the M110 and M220 Windows drivers only have one BLOCK MARKER, even for long label output.

And I do not have M02.

So I do not understand why the M02 filter intentionally inserts a BLOCK MARKER (i.e. GS v 0 command) every 255 lines. Is this some kind of workaround for a problem specific to M02? Or was the captured packet formed that way?

**Comment by vivier** [comment]
Please merge the 3 commits in 1.
(you can use "git rebase -i HEAD~3" and then replace the 2 last "pick" by "fixup")

**Comment by vivier** [comment]
Closing the pull request as I don't know if it is relevant anymore.

**Comment by geeksville** [comment]
Hi @vivier FWIW my M220 didn't work without this PR applied.  I've pulled it into my branch and will send in a new PR soon I'll squash the changes by @bleriotx into a single commit and also add a commit I needed to add to support the wider prints allowed by the M220.  (70mm wide by 80mm high).  For the latter I needed to copy the m110 ppd+drv and modify it to add the new page sizes).

**Pull request closed without merging**
